# On my laptop I use python 3.11.4 (homebrew)
# Do I need here to have a source as close as possible?
# Python 3.10-slim seems to download over 500 mb...
# 
# So can I also use a small package like Alpine or Python stretch?


FROM python:stretch

# Directoy for code
COPY . /app
WORKDIR /app

# Install 'pip' and required Python packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Endpoint with 'gunicorn WSGI server'
ENTRYPOINT ["gunicorn", "-b", ":8080", "main:APP"]